CREATE TABLE IF NOT EXISTS person (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS account (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    owner_person_id UUID NULL REFERENCES person(id)
);

CREATE TABLE IF NOT EXISTS category (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(20) NOT NULL
        CHECK (type IN ('FIXED', 'VARIABLE')),
    active BOOLEAN NOT NULL DEFAULT TRUE
);
