ALTER TABLE person
    ADD COLUMN IF NOT EXISTS daily_spending_percentage NUMERIC(5, 2) NOT NULL DEFAULT 25,
    ADD COLUMN IF NOT EXISTS contribution_minimum NUMERIC(12, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bonus_months INTEGER[] NOT NULL DEFAULT ARRAY[6, 12]::INTEGER[],
    ADD COLUMN IF NOT EXISTS emergency_fund_months INTEGER NOT NULL DEFAULT 6;

CREATE TABLE IF NOT EXISTS person_income (
    id UUID PRIMARY KEY,
    person_id UUID NOT NULL REFERENCES person(id),
    amount NUMERIC(12, 2) NOT NULL,
    valid_from DATE NOT NULL
);
